import "../../globals.css";
import localFont from "next/font/local";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("store/provider"), {
  ssr: false,
});

import NextTopLoader from "nextjs-toploader";
export const metadata = {
  title: "TryDos",
  description: "Generated by create next app",
};
const sf_pro_display = localFont({
  src: "../../../public/fonts/SF-Pro-Display-Regular.woff",
  variable: "--SF-Pro-Rounded-Display",
});
const sf_pro_rounded_light = localFont({
  src: "../../../public/fonts/SF-Pro-Rounded-light.woff2",
  variable: "--SF-Pro-Rounded-Light",
});
const sf_pro_rounded_semibold = localFont({
  src: "../../../public/fonts/SF-Pro-Rounded-normal.woff2",
  variable: "--SF-Pro-Rounded-semibold",
});
const sf_pro_rounded_regular = localFont({
  src: "../../../public/fonts/SF-Pro-Rounded-Regular.woff2",
  variable: "--SF-Pro-Rounded-Regular",
});
const sf_pro_rounded_medium = localFont({
  src: "../../../public/fonts/SF-Pro-Rounded-normal.woff2",
  variable: "--SF-Pro-Rounded-Medium",
});
export default function RootLayout({ params: { lang }, children }) {
  return (
    <html
        className={`${sf_pro_display.variable} 
      ${sf_pro_rounded_light.variable} 
      ${sf_pro_rounded_semibold.variable} 
      ${sf_pro_rounded_regular.variable} 
      ${sf_pro_rounded_medium.variable} font-sans`}
        lang={lang}>
      <link rel="icon" href="/favicon.ico" sizes="any" />
       {/*

       usage fonts

       <div className={ ' font-sf_pro_rounded_medium  ' } ></div>

       */}
      <body>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          zIndex={1600}
          showAtBottom={false}
        />
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K8QKJJLK"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
